### ISSUE TITLE
do you have an example of meteor-os like you do the underlying manager lib?

### ISSUE THREAD

**Issue by faceyspacey** [jchristman/meteor-os#1]

**Comment by jchristman** [comment]
@faceyspacey, I do not currently have a running instance of the library, but you could clone into the example and run it. By default, there are 26 users created with username 'a'-'z' and password 'asdf' for you to login with. I'm currently doing some heavy dev, so you may experience some unstable behaviors.

There are two builtin apps so far that provide a template on how to work with the MeteorOS layer on top of [meteor-application-manager](https://github.com/jchristman/meteor-application-manager): a File Browser with drag and drop file uploads, and a settings app that I just wrote that has a working team management component.

```
git clone https://github.com/jchristman/meteor-os
cd meteor-os/example
meteor
```

A couple of notes on the state of MeteorOS. I'm decently satisfied with the overall system and have the following TODO list on it:
1. Finish file sharing model. I just finished a team management app that works pretty well (if you start the "Settings" app from the "Start Menu") and I am currently rewriting the file system into the builtins/file-browser app.
2. Finish the settings app to include profile management and UI settings.
3. Make the app windows be able to popout. I just wrote a library that does this. [jchristman:popout](https://atmospherejs.com/jchristman/popout)
4. Make the entire UI system look less crappy.
5. Make the background image customizable.
6. Write better right click menus
7. Make applications "minimize" into the "taskbar" at the bottom of the page
8. Write chat into the system. Possibly build into the taskbar in the bottom right corner (like Facebook)?
